# Generated by Django 3.0.2 on 2020-11-04 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category_parent',
            fields=[
                ('categoryParent_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_principal', models.ImageField(blank=True, default='productDefault.png', null=True, upload_to='')),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('specs', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SecundaryImage',
            fields=[
                ('SecundaryImage_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_principal', models.ImageField(blank=True, default='productDefault.png', null=True, upload_to='')),
                ('active', models.BooleanField()),
                ('order', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('Discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category_parent'),
        ),
    ]
