# Generated by Django 3.0.2 on 2020-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('imagen_principal', models.ImageField(blank=True, default='produtDefault.png', null=True, upload_to='')),
                ('precio', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField()),
                ('specs', models.TextField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
