# Generated by Django 3.0.2 on 2020-09-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200917_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
