# Generated by Django 3.0.2 on 2020-11-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_secundaryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecundaryImage',
        ),
    ]
