# Generated by Django 3.0.2 on 2020-11-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_secundaryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secundaryimage',
            old_name='imagen_principal',
            new_name='imagen',
        ),
    ]
