# Generated by Django 3.0.2 on 2020-11-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201104_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garantia',
            field=models.IntegerField(default=6),
        ),
    ]
