# Generated by Django 3.0.2 on 2020-09-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200917_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
