# Generated by Django 3.0.2 on 2020-09-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200918_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category_parent',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
