# Generated by Django 3.0.2 on 2020-09-23 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('Discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
        ),
    ]
