# Generated by Django 3.0.2 on 2020-09-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200917_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
