# Generated by Django 3.0.2 on 2020-09-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200917_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
